"""Add LogEntry table

Revision ID: 605b23e7d3ba
Revises: 3b62eabfb5e5
Create Date: 2025-05-30 17:57:26.210923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605b23e7d3ba'
down_revision = '3b62eabfb5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('cleared', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_entry')
    # ### end Alembic commands ###
