"""add balance fields to log entry

Revision ID: 8fb20a7b74de
Revises: 605b23e7d3ba
Create Date: 2025-05-30 21:45:26.210923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb20a7b74de'
down_revision = '605b23e7d3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_balance', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('pending_total', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('cleared_balance', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('available_balance', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.drop_column('available_balance')
        batch_op.drop_column('cleared_balance')
        batch_op.drop_column('pending_total')
        batch_op.drop_column('starting_balance')

    # ### end Alembic commands ###
